/**
 * PilSim shared contracts. FROZEN — owned by the lead.
 *
 * Do not edit this file. Every module binds to these types; changing one breaks
 * the others silently. If you need a new type, declare it in your own module.
 *
 * EffectFrame is normative and comes from research/04-ORGAN-EFFECT-MAP.md §2.
 * Field names and units are exactly as specified there.
 */

// ---------------------------------------------------------------------------
// Provenance — every numeric value in the data files is wrapped like this.
// See data/substances.json `provenance_legend`.
// ---------------------------------------------------------------------------

export type ProvenanceStatus = 'CITED' | 'ESTIMATED' | 'NOT_FOUND'

/** Tier 1 = regulatory labeling, 2 = peer-reviewed, 3 = physicochemical DB, 4 = secondary. */
export type SourceTier = 1 | 2 | 3 | 4

export interface Provenance {
  status: ProvenanceStatus
  source?: string
  url?: string
  /** The value as the source words it. */
  quote?: string
  retrieved?: string
  tier?: SourceTier
  /** Justification when ESTIMATED, or what was searched when NOT_FOUND. */
  note?: string
  confidence?: 'LOW' | 'MEDIUM' | 'HIGH'
  conflicting_sources?: unknown[]
}

/** A numeric value with its uncertainty and where it came from. */
export interface Measured {
  value: number | null
  unit?: string
  range?: [number, number] | null
  cv_percent?: number | null
  n?: number | null
  distribution?: string | null
  provenance: Provenance
}

// ---------------------------------------------------------------------------
// The effect bus. NORMATIVE — research/04-ORGAN-EFFECT-MAP.md §2.
// The engine emits one of these per output step; the UI binds animation to it.
// ---------------------------------------------------------------------------

export type DrugId =
  | 'lisinopril'
  | 'losartan'
  | 'exp3174'
  | 'amlodipine'
  | 'hydrochlorothiazide'
  | 'metoprolol'

export interface EffectFrame {
  /** Simulated time, hours since first dose. */
  t_h: number

  /** Plasma concentrations, ng/mL. */
  conc: Record<DrugId, number>

  /** Target engagement, all fractions in [0,1]. */
  engagement: {
    ace_inhibition_plasma: number
    ace_inhibition_pulmonary: number
    ace_inhibition_renal: number
    /** losartan + EXP3174 together */
    at1_blockade: number
    cav12_block_vsmc: number
    /** near 0 for amlodipine — vascular selective */
    cav12_block_myocardium: number
    ncc_inhibition: number
    /** driven by losartan PARENT, not the metabolite */
    urat1_inhibition: number
    beta1_occupancy: number
    /** airway beta-2 — this is the selectivity-loss channel */
    beta2_occupancy: number
  }

  mediators: {
    renin_pra: number
    renin_pra_fold: number
    ang_ii: number
    ang_ii_fold: number
    aldosterone: number
    aldosterone_fold: number
    bradykinin_fold: number
    sympathetic_tone_fold: number
  }

  haemo: {
    sbp: number
    dbp: number
    map: number
    hr: number
    stroke_volume: number
    cardiac_output: number
    svr: number
    arteriolar_radius_index: number
    venous_tone_index: number
    capillary_hydrostatic_p: number
    contractility_index: number
  }

  renal: {
    gfr: number
    renal_blood_flow: number
    filtration_fraction: number
    p_glomerular: number
    afferent_radius_index: number
    efferent_radius_index: number
    na_excretion_rate: number
    k_excretion_rate: number
    urate_excretion_rate: number
    urine_flow: number
    frac_na_reab_pt: number
    frac_na_reab_tal: number
    /** distal convoluted tubule — the hydrochlorothiazide target */
    frac_na_reab_dct: number
    frac_na_reab_cd: number
  }

  chem: {
    plasma_volume: number
    ecf_volume: number
    serum_k: number
    serum_na: number
    serum_urate: number
    serum_creatinine: number
    fasting_glucose: number
  }

  periph: {
    interstitial_volume_index: number
    /** 0..3 clinical pitting scale */
    edema_grade: number
  }

  liver: {
    cyp3a4_flux: number
    cyp2c9_flux: number
    cyp2d6_flux: number
    cyp2d6_capacity_fold: number
    first_pass_extraction: {
      losartan: number
      amlodipine: number
      metoprolol: number
    }
  }

  lung: {
    fev1_pct_baseline: number
    airway_smooth_muscle_tone_index: number
    bradykinin_airway_fold: number
    cough_hazard: number
  }

  /** All 0..1. */
  hazards: {
    cough: number
    dizziness_orthostatic: number
    peripheral_edema: number
    bradycardia: number
    bronchospasm: number
    hyperkalemia: number
    [k: string]: number
  }
}

/**
 * Provenance tier for EffectFrame fields, per Agent E.
 * PROXY fields are uncalibrated indices and MUST NOT be rendered with absolute units.
 */
export type FrameFieldTier = 'COMPUTED' | 'DERIVED' | 'PROXY'

// ---------------------------------------------------------------------------
// Patient / digital twin
// ---------------------------------------------------------------------------

export type Sex = 'male' | 'female'
export type Cyp2d6Phenotype = 'poor' | 'intermediate' | 'normal' | 'ultrarapid'
export type Cyp2c9Phenotype = 'poor' | 'intermediate' | 'normal'

export interface PatientInputs {
  age_years: number
  sex: Sex
  weight_kg: number
  height_cm: number
  /** Entered baseline. The twin calibrates to reproduce this exactly. */
  sbp_mmHg: number
  dbp_mmHg: number
  hr_bpm?: number
  serum_creatinine_mg_dl?: number
  /** Comorbidity preset ids from data/patient_model.json. */
  comorbidities: string[]
  cyp2d6?: Cyp2d6Phenotype
  cyp2c9?: Cyp2c9Phenotype
  pregnant?: boolean
  [k: string]: unknown
}

/** Resolved twin state after the derivation pipeline runs. */
export interface PatientState {
  inputs: PatientInputs
  /** Every state variable from data/patient_model.json, keyed by its id. */
  vars: Record<string, number>
  /** Which comorbidity presets were applied. */
  appliedPresets: string[]
  /** Non-fatal problems encountered during derivation (out-of-range clamps etc). */
  warnings: string[]
}

// ---------------------------------------------------------------------------
// Regimens
// ---------------------------------------------------------------------------

export interface DoseSpec {
  substanceId: DrugId
  /** Milligrams of the named substance per administration. */
  mg: number
  /** Administrations per day. */
  perDay: number
  /**
   * Dosage form, matching a `formulations[].form` string in substances.json —
   * e.g. 'immediate-release tablet', 'extended-release tablet (metoprolol
   * succinate, multiple-unit pellet)', 'oral solution'.
   *
   * Omitted means the drug's default immediate-release oral form. Only some
   * forms differ pharmacokinetically: metoprolol's extended-release has
   * f_relative 0.77 and tmax 6.5 h against the tablet's 1.0 and 1.75 h, and
   * hydrochlorothiazide's capsule peaks earlier than its tablet. Where a form
   * exists but is pharmacokinetically equivalent, say so rather than inventing
   * a difference — and where `exists_real_world` is false, the product must
   * refuse rather than simulate a product that does not exist.
   */
  form?: string
}

export interface Regimen {
  id: string
  label: string
  doses: DoseSpec[]
}

// ---------------------------------------------------------------------------
// Rules engine. Schema documented in data/rules.json and research/C-notes.md.
// ---------------------------------------------------------------------------

export type SeverityId =
  | 'info'
  | 'preferred'
  | 'compelling'
  | 'minor'
  | 'moderate'
  | 'major'
  | 'contraindicated_relative'
  | 'contraindicated_absolute'

export interface RuleHit {
  ruleId: string
  title: string
  severity: SeverityId
  severityRank: number
  /** Only rank 7 hard-blocks. */
  blocks: boolean
  direction: 'negative' | 'positive' | 'modifier'
  mechanism: string
  warningText?: string
  effects: RuleEffect[]
  citation?: Provenance
}

export interface RuleEffect {
  op:
    | 'block'
    | 'require_override'
    | 'pk_multiply'
    | 'pd_multiply'
    | 'state_shift'
    | 'risk_set'
    /**
     * Multiplies an already-established risk probability by a subgroup factor.
     * Added after the initial 13 ops to carry the amlodipine oedema sex split.
     * Distinct from risk_set: risk_set establishes a probability, risk_modify
     * scales one. Consumers must gate it on `effect.substance`.
     */
    | 'risk_modify'
    | 'dose_cap'
    | 'dose_start'
    | 'titration_interval_days'
    | 'phenoconvert'
    | 'score_delta'
    | 'monitor'
    | 'annotate_organ'
  [k: string]: unknown
}

/** What the rules engine hands the simulation engine before a run. */
export interface RuleModifiers {
  hits: RuleHit[]
  blocked: boolean
  blockReasons: string[]
  /** Multiplicative PK adjustments, keyed by drug id. */
  pkMultipliers: Partial<Record<DrugId, number>>
  /** Multiplicative PD adjustments, keyed by drug id. */
  pdMultipliers: Partial<Record<DrugId, number>>
  /** Absolute shifts applied to baseline twin state variables. */
  stateShifts: Record<string, number>
  /** Dose ceilings in mg, keyed by drug id. */
  doseCaps: Partial<Record<DrugId, number>>
  /** Phenotype coercions, e.g. strong CYP2D6 inhibitor forces activity score 0. */
  phenoconversions: Record<string, string>
}

// ---------------------------------------------------------------------------
// Worker protocol — main thread <-> engine Web Worker
// ---------------------------------------------------------------------------

export interface SimRequest {
  kind: 'run'
  runId: string
  patient: PatientState
  regimen: Regimen
  modifiers: RuleModifiers
  options: {
    /** Simulated hours for the acute run. */
    horizonHours: number
    /** Emit one EffectFrame every N simulated minutes. */
    outputEveryMin: number
    /**
     * Start from steady state (default, correct for chronic dosing comparison)
     * or from the very first dose. first_dose disables regimen comparison.
     */
    initial: 'steady_state' | 'first_dose'
    /** Virtual population size. 1 = the single twin. */
    populationN?: number
    seed?: number
  }
}

export interface SimProgress {
  kind: 'frame'
  runId: string
  frame: EffectFrame
}

export interface SimDone {
  kind: 'done'
  runId: string
  /** Summary metrics used by the report and the ranker. */
  summary: RunSummary
}

export interface SimError {
  kind: 'error'
  runId: string
  message: string
}

export type SimResponse = SimProgress | SimDone | SimError

export interface RunSummary {
  /** Placebo-corrected steady-state reduction, mmHg. */
  deltaSbp: number
  deltaDbp: number
  /** Population spread when populationN > 1. */
  deltaSbpP05?: number
  deltaSbpP95?: number
  peakConc: Partial<Record<DrugId, number>>
  troughConc: Partial<Record<DrugId, number>>
  /** Cumulative adverse-event probabilities over the horizon, 0..1. */
  hazards: Record<string, number>
  finalChem: EffectFrame['chem']
  framesEmitted: number
}

// ---------------------------------------------------------------------------
// Report / scoring — research/05-OUTPUT-REPORT-SPEC.md
// ---------------------------------------------------------------------------

export interface ScoreWeights {
  efficacy: number
  safety: number
  tolerability: number
  /** Exposed as UI sliders — all ESTIMATED, ordering defensible, values not. */
  [k: string]: number
}

export interface RankedOption {
  regimen: Regimen
  score: number
  efficacyTerm: number
  safetyTerm: number
  deltaSbp: number
  /** Human-readable reasons, not just a number. */
  reasons: string[]
  hits: RuleHit[]
  /** Set when the product declines to rank — e.g. formulation data absent. */
  refusal?: { reason: string; citation?: Provenance }
}
